### ISSUE TITLE
cat: /var/data/in/my-example.fastq: No such file or directory

### ISSUE THREAD

**Issue by roko-t** [seqpod-examples/hello-world.ja#2]
修正されたimageを実行してみました
# pod-interface.yamlにおいて、inputsフィールドで指定されたものは、
# /var/data/in というディレクトリにすでに配置されています。

=> どの段階で配置するのですか？

**Comment by otiai10** [comment]
ユーザのインプットファイルが、コンテナの `/var/data/in` に配置されるのは、

1. SeqPod経由で動かした場合
2. podtk経由で動かした場合

に限ります。上記の場合で動かした場合、docker runが実行されるときに、ユーザのインプットファイルが物理的に配置されているディレクトリがコンテナの `/var/data/in` にマウントされます。

**Comment by otiai10** [comment]
したがって、デベロッパ自身が、dockerコマンドを直接叩いた場合は、それに相当するコマンドラインオプション `--volume` を自ら付加する必要があります。
